### ISSUE TITLE
Wrong extract path?

### ISSUE THREAD

**Issue by magedan** [hawezo/js-translation-bundle#1]
Hello!
Thank for this bundle, I found it more convenient than BazingaJsTranslationBundle (I use Symfony 4.3 + Webpack).
But it looks there is a small bug in exporting translation file.

Consider following bundle configuration:
```
js_translation:
    translation_extract_path: public/js/messages.js
    export_domains: ['messages']
```

There is a file dump in the JsTranslationExportCommand.php:
```
$filesystem->dumpFile(
    $this->root . '\\' . $this->export,
    $javascript);
```

On my Ubuntu installation I get message file dumped to /var/www/**project\public**/js/messages.js where "project\public" is a directory name. I believe the correct way would be to concatenate path using standard PHP constant:
```
$filesystem->dumpFile(
    $this->root . DIRECTORY_SEPARATOR . $this->export,
    $javascript);
```

**Comment by hawezo** [comment]
Hi,

Sorry for the trouble, but I moved this project on [javascript-bundle](https://github.com/hawezo/javascript-bundle) in order to have both routing and translation combined in the same bundle. 

I will set this repository on read-only, and I fixed this issue on the other one: https://github.com/hawezo/javascript-bundle/commit/203f714a13b740fd682feb5a906158ec939ec910.
