### ISSUE TITLE
Missing initialization

### ISSUE THREAD

**Issue by magedan** [hawezo/js-translation-bundle#2]
It looks like default behavior (`LoadTypes.LOAD_FROM_META`) doesn't put Translator into initialized state, so trans() method always failed because isInitialized() returns false.

I found that loadFromCatalogue() method has `this.initialized = true;` assignment, while loadFromMeta() doesn't have one.

Let me propose following adjustment:

```
    loadCatalogue() {
        switch (this.settings.loadType) {

            case LoadTypes.LOAD_FROM_CATALOGUE:
                this.loadFromCatalogue();
                break;

            case LoadTypes.LOAD_FROM_META:
                this.loadFromMeta();
                break;

            default:
                if (this.settings.debug) {
                    console.error('Invalid load type.');
                }
                return;
        }

        this.initialized = true; // <------

        return this;
    }
```

This way you can extract initialization logic from loadFrom*() methods and avoid code duplication.

**Comment by magedan** [comment]
Sorry, just realized that should be posted in https://github.com/hawezo/symfony-js-translator

**Comment by hawezo** [comment]
Hi,

Could you try [hawezo/symfony-javascript](https://github.com/hawezo/symfony-javascript) instead? I removed the `LoadType` functionnality in this one, because I found that large translation catalogues increase the page loading a lot, so my preferred method is by extraction.

That said, I fixed this and published it on NPM if you need to be able to load from meta tags.

Thanks for the suggestions.

**Comment by hawezo** [comment]
I'm closing this, but you can reopen if you need to.

**Comment by magedan** [comment]
> Could you try [hawezo/symfony-javascript](https://github.com/hawezo/symfony-javascript) instead? 

Sure, thanks a lot!
